#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqCustom
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DanhMucKH")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdm_khachhang(dm_khachhang instance);
    partial void Updatedm_khachhang(dm_khachhang instance);
    partial void Deletedm_khachhang(dm_khachhang instance);
    #endregion
		
		public DataDataContext() : 
				base(global::LinqCustom.Properties.Settings.Default.DanhMucKHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dm_khachhang> dm_khachhangs
		{
			get
			{
				return this.GetTable<dm_khachhang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dm_khachhang")]
	public partial class dm_khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _khachhang_loai;
		
		private string _khachhang_ma;
		
		private string _khachhang_mst;
		
		private string _khachhang_ten;
		
		private string _khachhang_ghichu;
		
		private string _doanhnghiep_mst;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onkhachhang_loaiChanging(System.Nullable<int> value);
    partial void Onkhachhang_loaiChanged();
    partial void Onkhachhang_maChanging(string value);
    partial void Onkhachhang_maChanged();
    partial void Onkhachhang_mstChanging(string value);
    partial void Onkhachhang_mstChanged();
    partial void Onkhachhang_tenChanging(string value);
    partial void Onkhachhang_tenChanged();
    partial void Onkhachhang_ghichuChanging(string value);
    partial void Onkhachhang_ghichuChanged();
    partial void Ondoanhnghiep_mstChanging(string value);
    partial void Ondoanhnghiep_mstChanged();
    #endregion
		
		public dm_khachhang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khachhang_loai", DbType="Int")]
		public System.Nullable<int> khachhang_loai
		{
			get
			{
				return this._khachhang_loai;
			}
			set
			{
				if ((this._khachhang_loai != value))
				{
					this.Onkhachhang_loaiChanging(value);
					this.SendPropertyChanging();
					this._khachhang_loai = value;
					this.SendPropertyChanged("khachhang_loai");
					this.Onkhachhang_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khachhang_ma", DbType="VarChar(50)")]
		public string khachhang_ma
		{
			get
			{
				return this._khachhang_ma;
			}
			set
			{
				if ((this._khachhang_ma != value))
				{
					this.Onkhachhang_maChanging(value);
					this.SendPropertyChanging();
					this._khachhang_ma = value;
					this.SendPropertyChanged("khachhang_ma");
					this.Onkhachhang_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khachhang_mst", DbType="VarChar(50)")]
		public string khachhang_mst
		{
			get
			{
				return this._khachhang_mst;
			}
			set
			{
				if ((this._khachhang_mst != value))
				{
					this.Onkhachhang_mstChanging(value);
					this.SendPropertyChanging();
					this._khachhang_mst = value;
					this.SendPropertyChanged("khachhang_mst");
					this.Onkhachhang_mstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khachhang_ten", DbType="VarChar(255)")]
		public string khachhang_ten
		{
			get
			{
				return this._khachhang_ten;
			}
			set
			{
				if ((this._khachhang_ten != value))
				{
					this.Onkhachhang_tenChanging(value);
					this.SendPropertyChanging();
					this._khachhang_ten = value;
					this.SendPropertyChanged("khachhang_ten");
					this.Onkhachhang_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khachhang_ghichu", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string khachhang_ghichu
		{
			get
			{
				return this._khachhang_ghichu;
			}
			set
			{
				if ((this._khachhang_ghichu != value))
				{
					this.Onkhachhang_ghichuChanging(value);
					this.SendPropertyChanging();
					this._khachhang_ghichu = value;
					this.SendPropertyChanged("khachhang_ghichu");
					this.Onkhachhang_ghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanhnghiep_mst", DbType="VarChar(50)")]
		public string doanhnghiep_mst
		{
			get
			{
				return this._doanhnghiep_mst;
			}
			set
			{
				if ((this._doanhnghiep_mst != value))
				{
					this.Ondoanhnghiep_mstChanging(value);
					this.SendPropertyChanging();
					this._doanhnghiep_mst = value;
					this.SendPropertyChanged("doanhnghiep_mst");
					this.Ondoanhnghiep_mstChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
